[package]
name = "wasmide"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Lefebvre"]
categories = ["wasm", "web-programming"]
description = "An experimental frontend framework in pure rust"
keywords = ["framework", "wasm", "web"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/L-Benjamin/wasmide"

[workspace]
members = [
    "examples/counter",
    "examples/hello-world",
]

[profile.release]
lto = "thin"
opt-level = "s"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

[dependencies.once_cell]
version = "1"
default-features = false

[dependencies.wasm-bindgen]
version = "0.2.83"
default-features = false

[dependencies.web-sys]
version = "0.3.60"
default-features = false
features = [
    "Document",
    "HtmlElement",
    "Node",
    "Window",
]