// Programmatically generated by scripts/codegen.py, do not edit manually.
//! HTML elements and attributes definitions.
//! 
//! In the Wasmadeus framework, [HTML elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) are replaced
//! with simple rust functions taking one or more [`Attributes`]
//! for input and yielding a [`Component`].
//! 
//! [HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) are simply rust structs that implement 
//! the [`Attribute`] trait.
//!
//! This module contains the definitions and documentation of all standard HTML 
//! elements and attributes, including the deprecated and experimental ones.

use crate::attribute::attributes;
use crate::component::elements;


attributes! {
}

elements! {
}
